services:
  voluming-example:
    build:
      context: .
      dockerfile: voluming.Dockerfile
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - cache-volume:/cache

volumes:
  cache-volume: {}
